#!/usr/bin/env node
/**
 * gen-strings.mjs — locale JSON → Android strings.xml 转换器
 *
 * 用法: node tools/gen-strings.mjs <locale目录> <res输出目录>
 *   例: node tools/gen-strings.mjs <locale 目录> app/src/main/res
 *
 * 转换规则:
 *  - 只转换 ACTIVE_NS 中的活 namespace；死 namespace 不转
 *  - 键名扁平化: {ns}_{key 路径}
 *  - 命名插值 {name} → Android 位置参数 %<i>$s（索引按 en 文本出现顺序；
 *    两语言的插值名集合必须一致，否则报错退出）
 *  - 断言: 两语言扁平键集合完全一致（两语言必须同步增删）
 *  - 生成文件为 values 与 values-en 目录下的 strings_generated.xml（手写资源在 strings.xml，互不覆盖）
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// 只转换下列 26 个活 namespace（其余为死键，不转）
const ACTIVE_NS = [
  'common', 'device_list', 'home', 'network', 'client', 'statistics',
  'reboot', 'tabbar', 'language', 'route', 'process', 'startup', 'diag',
  'syslog', 'conntrack', 'apps', 'arpbind', 'wolultra', 'autoreboot',
  'cifs', 'samba', 'upnp', 'wifi', 'firewall', 'usb_printer', 'passwall2',
];

const [localeDir, resDir] = process.argv.slice(2);
if (!localeDir || !resDir) {
  console.error('用法: node tools/gen-strings.mjs <locale目录> <res输出目录>');
  process.exit(1);
}

// 语义修正（文案冻结，覆盖在转换层做）：
// 既有文案含过期指引（新核心默认接受自签证书，指引已不成立）
const OVERRIDES = {
  device_list_error_certificate: {
    zh: 'SSL 证书验证失败，请检查设备的 HTTPS 配置',
    en: 'SSL certificate verification failed. Check the device HTTPS configuration',
  },
  // 2026-09-19 首页二轮：卡片定名（系统状态→系统信息、网络状态→网络信息）
  home_system_status: {
    zh: '系统信息',
    en: 'System info',
  },
  home_network_status: {
    zh: '网络信息',
    en: 'Network info',
  },
  // 「连接数」实为 conntrack 会话数（当前/上限），改名避免误读为在线设备数
  home_connections: {
    zh: 'NAT 会话',
    en: 'NAT sessions',
  },
};

// 不迁移的键（两语言都有，不触发孤儿断言，需显式丢弃；均已核实新仓库零引用）：
// - device_list_ping_hint: "延迟为 HTTP 响应时间，仅供参考"——延迟已是真 ICMP ping，提示不再成立
const DROP_KEYS = new Set(['device_list_ping_hint']);

const zh = JSON.parse(readFileSync(join(localeDir, 'zh-Hans.json'), 'utf8'));
const en = JSON.parse(readFileSync(join(localeDir, 'en.json'), 'utf8'));

const PLACEHOLDER = /\{([A-Za-z_]\w*)\}/g;
const XML_ESCAPES = [
  [/&/g, '&amp;'], [/</g, '&lt;'], [/>/g, '&gt;'],
];

function flatten(lang, ns) {
  if (!(ns in lang)) throw new Error(`namespace 缺失: ${ns}`);
  const out = new Map();
  const walk = (node, prefix) => {
    for (const [key, value] of Object.entries(node)) {
      const full = prefix ? `${prefix}_${key}` : key;
      if (value && typeof value === 'object') walk(value, full);
      else out.set(full, String(value));
    }
  };
  walk(lang[ns], ns);
  return out;
}

function escapeXml(text) {
  let s = text;
  for (const [re, to] of XML_ESCAPES) s = s.replace(re, to);
  // Android 字符串中的撇号必须转义，否则 aapt 报错
  s = s.replace(/'/g, "\\'");
  return s;
}

/** 把 {name} 插值换成 %<i>$s；索引由 indexByName（名字→序号）决定 */
function toAndroidFormat(text, indexByName) {
  let s = text.replace(PLACEHOLDER, (_, name) => {
    if (!indexByName.has(name)) throw new Error(`未登记的插值: {${name}} in "${text}"`);
    return `%${indexByName.get(name)}$s`;
  });
  // 裸 % 会被 aapt 当作格式化占位符报错，转成 %%
  s = s.replace(/%(?!\d+\$)/g, '%%');
  return s;
}

// 1) 扁平化 + 键集合断言
const flat = {};
const dropped = [];
let placeholderCount = 0;
for (const ns of ACTIVE_NS) {
  const zhMap = flatten(zh, ns);
  const enMap = flatten(en, ns);
  const zhKeys = new Set(zhMap.keys());
  const enKeys = new Set(enMap.keys());
  // 单语言孤儿键 = 两语言键不同步的历史残留（均已核实零引用）：
  // 跳过并大声警告，不静默；两语言共有的键仍严格执行插值对齐断言
  const onlyZh = [...zhKeys].filter((k) => !enKeys.has(k));
  const onlyEn = [...enKeys].filter((k) => !zhKeys.has(k));
  for (const k of onlyZh) dropped.push(`${ns}:${k}(仅中文)`);
  for (const k of onlyEn) dropped.push(`${ns}:${k}(仅英文)`);
  for (const key of zhKeys) {
    if (!enKeys.has(key) || DROP_KEYS.has(key)) continue;
    const zhText = zhMap.get(key);
    const enText = enMap.get(key);
    const zhNames = [...zhText.matchAll(PLACEHOLDER)].map((m) => m[1]).sort();
    const enNames = [...enText.matchAll(PLACEHOLDER)].map((m) => m[1]).sort();
    if (JSON.stringify(zhNames) !== JSON.stringify(enNames)) {
      console.error(`❌ ${key}: 两语言插值名不一致 zh={${zhNames}} en={${enNames}}`);
      process.exit(1);
    }
    // 索引按 en 文本首次出现顺序
    const indexByName = new Map();
    for (const m of enText.matchAll(PLACEHOLDER)) {
      if (!indexByName.has(m[1])) indexByName.set(m[1], indexByName.size + 1);
    }
    if (indexByName.size) placeholderCount++;
    flat[key] = {
      zh: escapeXml(toAndroidFormat(OVERRIDES[key]?.zh ?? zhText, indexByName)),
      en: escapeXml(toAndroidFormat(OVERRIDES[key]?.en ?? enText, indexByName)),
    };
  }
}

// 2) 输出（资源名安全化：仅 [a-z0-9_]）
const safeName = (key) => key.toLowerCase().replace(/[^a-z0-9_]/g, '_');
const emit = (langKey) => {
  const lines = ['<?xml version="1.0" encoding="utf-8"?>', '<!-- Generated by tools/gen-strings.mjs — DO NOT EDIT -->', '<resources>'];
  for (const [key, pair] of Object.entries(flat)) {
    lines.push(`    <string name="${safeName(key)}">${pair[langKey]}</string>`);
  }
  lines.push('</resources>', '');
  return lines.join('\n');
};

const zhOut = join(resDir, 'values');
const enOut = join(resDir, 'values-en');
mkdirSync(zhOut, { recursive: true });
mkdirSync(enOut, { recursive: true });
writeFileSync(join(zhOut, 'strings_generated.xml'), emit('zh'));
writeFileSync(join(enOut, 'strings_generated.xml'), emit('en'));

console.log(`✅ 生成完成: ${Object.keys(flat).length} 条 × 2 语言（含插值的字符串 ${placeholderCount} 条）`);
if (dropped.length) {
  console.warn(`⚠️ 丢弃单语言孤儿键 ${dropped.length} 个（两语言键不同步的历史残留，均已核实零引用）:`);
  for (const d of dropped) console.warn(`   - ${d}`);
}
console.log(`   ${join(zhOut, 'strings_generated.xml')}`);
console.log(`   ${join(enOut, 'strings_generated.xml')}`);
