#!/usr/bin/env node
/**
 * svg2vector.mjs — 品牌图标 SVG → Android VectorDrawable 批量转换器
 *
 * 用法: node tools/svg2vector.mjs
 * 输入: tools/vendor-svgs/*.svg（源 = luci-app-oui 打包的 simple-icons CC0 图标
 *       + 3 个 wikimedia 公有领域补充图标，见 app/src/main/assets/oui/NOTICE.supplemental；
 *       商标归各厂商，simple-icons 要求分发时阅读其 disclaimer）
 * 数据: app/src/main/assets/oui/vendors.json 的 vendors 数组（[slug, 显示名]）是
 *       slug 唯一事实源——只生成库内 slug 的图标
 * 输出: app/src/main/res/drawable/vendor_<slug>.xml
 *       app/src/main/kotlin/dev/wrtctrl/ui/screen/VendorIcons.kt（slug → R.drawable 封闭映射）
 *
 * VectorDrawable 说明：全部图标 viewBox=0 0 24 24；单色 path（fill 由 Compose tint 控制，
 * 固定写 #FF000000）；fill-rule="evenodd" → android:fillType。
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { join, basename } from 'node:path';

const root = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const svgDir = join(root, 'tools', 'vendor-svgs');
const resDir = join(root, 'app', 'src', 'main', 'res', 'drawable');
const ktPath = join(root, 'app', 'src', 'main', 'kotlin', 'dev', 'wrtctrl', 'ui', 'screen', 'VendorIcons.kt');
const vendorsJson = join(root, 'app', 'src', 'main', 'assets', 'oui', 'vendors.json');

const vendors = JSON.parse(readFileSync(vendorsJson, 'utf8')).vendors.map(([slug]) => slug);
const available = new Set(readdirSync(svgDir).filter((f) => f.endsWith('.svg')).map((f) => f.replace(/\.svg$/, '')));

// 复杂源图标不走本脚本的正则转换（CorelDRAW/Inkscape 导出：渐变/transform/CSS class）：
// - midea / gigabyte：一次性经 `npx svg2vectordrawable` 转换，产物已提交，勿覆盖
// - tcl：转换产物损坏（空 pathData），不提供品牌图标，运行时回落通用 Devices 图标
const EXTERNAL = new Set(['midea', 'gigabyte', 'tcl']);

const drawableExists = (slug) => {
  try {
    readFileSync(join(resDir, `vendor_${slug}.xml`));
    return true;
  } catch {
    return false;
  }
};

mkdirSync(resDir, { recursive: true });

const generated = [];
for (const slug of vendors) {
  if (EXTERNAL.has(slug)) continue;
  if (!available.has(slug)) {
    console.warn(`⚠️ 跳过 ${slug}（无源 SVG）`);
    continue;
  }
  const svg = readFileSync(join(svgDir, `${slug}.svg`), 'utf8');
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1] ?? '0 0 24 24';
  const [, , w, h] = viewBox.split(/\s+/).map(Number);
  const paths = [...svg.matchAll(/<path\b([^>]*?)\/?>/g)].map(([, attrs]) => {
    const d = attrs.match(/\bd="([^"]+)"/)?.[1];
    if (!d) throw new Error(`${slug}: path 无 d 属性`);
    // d 属性内的 XML 转义还原（源里可能出现 &gt; 等，pathData 不该有但兜底）
    const pathData = d.replace(/&gt;/g, '>').replace(/&lt;/g, '<').replace(/&amp;/g, '&');
    const evenOdd = /fill-rule="evenodd"|clip-rule="evenodd"/.test(attrs);
    return { pathData, evenOdd };
  });
  if (paths.length === 0) throw new Error(`${svg}: 无 path 元素`);

  const body = paths
    .map(
      (p) =>
        `    <path\n        android:fillColor="#FF000000"\n` +
        (p.evenOdd ? `        android:fillType="evenOdd"\n` : '') +
        `        android:pathData="${p.pathData}" />`,
    )
    .join('\n');
  const xml =
    `<?xml version="1.0" encoding="utf-8"?>\n` +
    `<!-- Generated by tools/svg2vector.mjs from tools/vendor-svgs/${slug}.svg — DO NOT EDIT -->\n` +
    `<vector xmlns:android="http://schemas.android.com/apk/res/android"\n` +
    `    android:width="24dp"\n` +
    `    android:height="24dp"\n` +
    `    android:viewportWidth="${w}"\n` +
    `    android:viewportHeight="${h}">\n${body}\n</vector>\n`;
  writeFileSync(join(resDir, `vendor_${slug}.xml`), xml);
  generated.push(slug);
}

// 映射表只收录实际存在的 drawable（含 EXTERNAL 手工产物；坏产物删除后自动缺席）
const mapEntries = vendors
  .filter((slug) => generated.includes(slug) || (EXTERNAL.has(slug) && drawableExists(slug)))
  .map((slug) => `    "${slug}" to R.drawable.vendor_${slug},`)
  .join('\n');
const kt = `package dev.wrtctrl.ui.screen

import dev.wrtctrl.R

/**
 * 厂商 slug → 品牌 VectorDrawable 封闭映射（Generated by tools/svg2vector.mjs — DO NOT EDIT）。
 * 图标源：simple-icons（CC0）+ 3 个 wikimedia 公有领域补充图标，商标归各厂商；
 * 数据库见 assets/oui/vendors.json（macdb，MIT），许可文件随 assets 分发。
 */
internal val VENDOR_DRAWABLES: Map<String, Int> = mapOf(
${mapEntries}
)
`;
writeFileSync(ktPath, kt);

console.log(`✅ 生成 ${generated.length} 个 drawable + VendorIcons.kt（库内 ${vendors.length} 个 slug）`);
