package dev.wrtctrl.ui.screen

import dev.wrtctrl.R

/**
 * 厂商 slug → 品牌 VectorDrawable 封闭映射（Generated by tools/svg2vector.mjs — DO NOT EDIT）。
 * 图标源：simple-icons（CC0）+ 3 个 wikimedia 公有领域补充图标，商标归各厂商；
 * 数据库见 assets/oui/vendors.json（macdb，MIT），许可文件随 assets 分发。
 */
internal val VENDOR_DRAWABLES: Map<String, Int> = mapOf(
    "apple" to R.drawable.vendor_apple,
    "asus" to R.drawable.vendor_asus,
    "acer" to R.drawable.vendor_acer,
    "msi" to R.drawable.vendor_msi,
    "dell" to R.drawable.vendor_dell,
    "hp" to R.drawable.vendor_hp,
    "lenovo" to R.drawable.vendor_lenovo,
    "samsung" to R.drawable.vendor_samsung,
    "huawei" to R.drawable.vendor_huawei,
    "honor" to R.drawable.vendor_honor,
    "xiaomi" to R.drawable.vendor_xiaomi,
    "oppo" to R.drawable.vendor_oppo,
    "vivo" to R.drawable.vendor_vivo,
    "oneplus" to R.drawable.vendor_oneplus,
    "motorola" to R.drawable.vendor_motorola,
    "nokia" to R.drawable.vendor_nokia,
    "sony" to R.drawable.vendor_sony,
    "lg" to R.drawable.vendor_lg,
    "google" to R.drawable.vendor_google,
    "microsoft" to R.drawable.vendor_microsoft,
    "intel" to R.drawable.vendor_intel,
    "nvidia" to R.drawable.vendor_nvidia,
    "broadcom" to R.drawable.vendor_broadcom,
    "mediatek" to R.drawable.vendor_mediatek,
    "fujitsu" to R.drawable.vendor_fujitsu,
    "toshiba" to R.drawable.vendor_toshiba,
    "panasonic" to R.drawable.vendor_panasonic,
    "sharp" to R.drawable.vendor_sharp,
    "raspberrypi" to R.drawable.vendor_raspberrypi,
    "framework" to R.drawable.vendor_framework,
    "amazon" to R.drawable.vendor_amazon,
    "tplink" to R.drawable.vendor_tplink,
    "ubiquiti" to R.drawable.vendor_ubiquiti,
    "netgear" to R.drawable.vendor_netgear,
    "linksys" to R.drawable.vendor_linksys,
    "synology" to R.drawable.vendor_synology,
    "qnap" to R.drawable.vendor_qnap,
    "midea" to R.drawable.vendor_midea,
    "gigabyte" to R.drawable.vendor_gigabyte,
    "vmware" to R.drawable.vendor_vmware,
)
